### ISSUE TITLE
Admin launch checklist

### ISSUE THREAD

**Issue by vaclavbohac** [Demagog2/demagog#149]
Make sure the following is done:

## Legacy database:
* [x] latest version of legacy database is loaded into the system
* [x] automatic migrations from legacy database are turned off

## Nginx configuration 
* [x] nginx cache on production is turned off
* [x] make sure nginx does serve file with gzip encryption
* [x] raise file upload limit to, say, 2mb

## Rails configuration
* [x] configure activestorage for production environment
* [x] configure google oauth2 for production environment

## Launch
* [x] latest data are migrated
* [x] images are uploaded to activestorage in digitalocean spaces

## Other
* [x] transfer vyrocni zpravy from https://demagog.cz/diskuze/jak-je-projekt-demagogcz-financovan to digitalocean spaces
