### ISSUE TITLE
Heroku pre-launch checklist

### ISSUE THREAD

**Issue by vaclavbohac** [Demagog2/demagog#624]
* [x] website is running from demagog.cz domain
* [x] oauth to admin is working
* [x] elasticsearch cluster is reachable
* [x] sidekiq jobs are running

**Comment by vaclavbohac** [comment]
Done
